### PR TITLE
Fix: Deploying a single function 

### LINKED ISSUE #23: Plugin won't wrap functions deployed using `sls deploy -f`
Attempting to [deploy function](https://serverless.com/framework/docs/providers/aws/cli-reference/deploy-function/) will not trigger the plugin.  

This causes all sorts of mayhem.

For instance:
1. Service deployed using `sls deploy`
2. **Without changing the deployed function code**, deploy function `sls deploy -f fooBar`
3. Code won't change as Serverless will let us know `Serverless: Code not changed. Skipping function deployment.`
4. The handler however will get updated, and will now longer point to `_lumigo/fooBar.js` but rather `mypath/foo-bar.js`, and executing the function will fail to execute **in runtime** because the code does not exist there.

Attaching to the `function:deploy` lifecycle hook should do the trick.

Opened #24 to resolve this one

### PR DESCRIPTION
**Pull request by roni-frantchi**
Resolves #23 

- Fixed by wrapping the function in the `deploy:function` lifecycle as well.  
- Did some refactoring to be able to reuse existing code
- Added `nodejs` tests as well and DRYed up the code a little bit there as well

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -47,9 +50,19 @@ class LumigoPlugin {
...
 	}
 
+	async afterDeployFunctionInitialize() {
+		await this.wrapFunctions([this.options.function]);
+	}
+
 	async afterPackageInitialize() {
-		// [{"handler":"handler.hello","events":[],"name":"aws-nodejs-dev-hello"}]
-		const { runtime, functions } = this.getFunctionsToWrap(this.serverless.service);
+		await this.wrapFunctions();
```
Comment (efimk-lu) [inline src/index.js]: Are you missing here `service.getAllFunctions()` ?

File: src/index.js [hunk 2]
```diff
@@ -119,12 +132,15 @@ class LumigoPlugin {
...
-	getFunctionsToWrap(service) {
-		const functions = service.getAllFunctions().map(localName => {
-			const x = _.cloneDeep(service.getFunction(localName));
-			x.localName = localName;
-			return x;
-		});
+	getFunctionsToWrap(service, functionNames) {
+		const functions = service
+			.getAllFunctions()
+			.filter(localName => !functionNames || functionNames.includes(localName))
```
Comment (efimk-lu) [inline src/index.js]: I prefer to avoid `undefined` check, just pass everything if you want all functions or the specific function. It's confusing

File: src/index.test.js [hunk 3]
```diff
@@ -92,209 +94,155 @@ describe("Invalid plugin configuration", () => {
...
 
 describe("Lumigo plugin (node.js)", () => {
-	describe("nodejs8.10", () => {
-		beforeEach(() => {
-			serverless.service.provider.runtime = "nodejs8.10";
-		});
+	describe.each`
+		runtime         |
+		${"nodejs8.10"}
+		${"nodejs10.x"}
```
Comment (efimk-lu) [inline src/index.test.js]: image

File: src/index.js (hunk 1 above)
Comment (roni-frantchi) [reply src/index.js]: No it is done in `wrapFunctions()`

File: src/index.js (hunk 2 above)
Comment (roni-frantchi) [reply src/index.js]: I wanted to keep `functionNames` as an optional parameter.  
Passing `service.getAllFunctions()` names just to filter out any of those that aren't in that same set may subjectively be even more confusing.  

I have pushed [this change](https://github.com/lumigo-io/serverless-lumigo-plugin/pull/24/commits/87e2e82f496b5e5cec962d447ecf8219d1469fd1), Do you find it less confusing now?

**Comment by roni-frantchi** [comment]
> Definitely we need to add here an e2e test

That would be help 😇 

> did you run it once, verifying that the regular wrapping still works?

Yes I did. 
Tested as best I could with several different permutations of full service/single function deployments 
```
// package.json
"devDependencies:" {
...
    "serverless-lumigo": "https://github.com/env0/serverless-lumigo-plugin#fix-sls-deploy-function",
...
}
```

```
env0/services/account-service on  fix-lumigo-sls-deploy-function [$!] is 📦 v1.0.0 via ⬢ v10.15.0 
➜ sls deploy -s pr681

...

Serverless: serverless-lumigo: there are 14 function(s) to wrap...

...

Serverless: serverless-lumigo: wrapping [functions/get-account.handler]...
Serverless: serverless-lumigo: writing wrapper function to [/Users/roni/dev/env0/services/account-service/_lumigo/getAccount.js]...
Serverless: serverless-lumigo: setting [getAccount]'s handler to [_lumigo/getAccount.handler]...
...
```

But please, do give it a go yourself.

**Comment by efimk-lu** [comment]
@roni-frantchi I found an issue in the formatting, I'm fixing it internally and then I'll approve.

**Comment by efimk-lu** [comment]
@roni-frantchi merging. Found an issue in the way you wrote `describe.each` for some reason it did not run 10.X only 8.10. Fixed and pushed.

Thank you very much for your contribution!
